In [1]:
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [26]:
n1 = np.array((1,2.0,3,'j'))
print(n1)

['1' '2.0' '3' 'j']


In [28]:
type(n1)

numpy.ndarray

In [33]:
n=np.array(['hii',1,4.7,[0]], dtype=object)
print(n)
print(n.dtype)

['hii' 1 4.7 list([0])]
object


In [22]:
type(n)


numpy.ndarray

In [35]:
arr = np.array([1, "hello", [1,2,3]], dtype=object)
print(arr, arr.dtype)


[1 'hello' list([1, 2, 3])] object


In [38]:
type(arr)

numpy.ndarray

In [1]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]
c=[]
for i in range(len(a)):
    c.append(a[i]*b[i])
print(c)

[6, 14, 24, 36, 50]


In [6]:
r=int(input("Enter no.of rows:"))
cl=int(input("Enter no.of columns:"))
print("Enter elements of first matrics:")
a=[]
for i in range(r):
    row=list(map(int,input().split()))
    a.append(row)
print("Enter elements of second matrix:")
b=[]
for i in range(r):
    row=list(map(int,input().split()))
    b.append(row)
c=[]
for i in range(r):
    row=[]
    for j in range(cl):
        row.append(a[i][j]*b[i][j])
    c.append(row)
print("Matrix:")
for row in c:
    print(*row)

Enter no.of rows: 2
Enter no.of columns: 3


Enter elements of first matrics:


 1 2 3
 4 5 6


Enter elements of second matrix:


 7 8 9
 10 11 12


Matrix:
7 16 27
40 55 72


In [12]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(type(a))
b=np.array([6,7,8])
print(b)
print(type(b))

(3, 5)
15
2
int64
8
<class 'numpy.ndarray'>
[6 7 8]
<class 'numpy.ndarray'>


In [26]:
import numpy as np
a = np.array([2,4,6])
a

array([2, 4, 6])

In [27]:
a.dtype

dtype('int64')

In [28]:
b=np.array([1.2,3.4,5.6])
b

array([1.2, 3.4, 5.6])

In [29]:
b.dtype

dtype('float64')

In [32]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [34]:
b=np.array([(1.5,2,3),(4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [35]:
c=np.array([[1,2],[3,4]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [36]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [42]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [43]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [44]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [54]:
from numpy import pi
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [61]:
x=np.linspace(0,2*pi,100)
f=np.sin(x)

In [65]:
#Outliers
dt = [11, 10, 12, 14, 12, 15, 14, 13, 15, 102, 12, 14, 17, 191, 107, 
      10, 13, 12, 14, 12, 108, 12, 11, 14, 13, 15, 12, 10, 14, 13, 15, 10]



def outliers(x):
    thresh = 3
    mean = np.mean(x)
    std = np.std(x)
    outliers = []

    for i in  x:
        z_score = (i - mean) / std
        if np.abs(z_score) > thresh:
            outliers.append(i)

    return outliers

outliers(dt)

[191]

In [72]:
def myfunc(a,b,*,c=10):
    print(a,b,c)
myfunc(1,2,c=30)

1 2 30


In [83]:
from array import array
import math
a=array('l')
b=array('u','hello \u2641')
c=array('l',[1,2,3,4,5])
d=array('d',[1.0,2.0,3.14,-math.inf,math.nan])
print(a,b,c,d)

array('l') array('u', 'hello ♁') array('l', [1, 2, 3, 4, 5]) array('d', [1.0, 2.0, 3.14, -inf, nan])


In [3]:
import numpy as np
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [4]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [10]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [11]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [13]:
import sys
np.set_printoptions(threshold=sys.maxsize)

In [15]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [16]:
A@B

array([[5, 4],
       [3, 4]])

In [17]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x.dot(y))

32


In [27]:
rg=np.random.default_rng(1)
a=np.ones((2,3),dtype=int)
print(a)
b=rg.random((2,3))
print(b)
a*=3
print(a)
b+=a
print(b)
a+=b
print(a)

[[1 1 1]
 [1 1 1]]
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
[[3 3 3]
 [3 3 3]]
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [4]:
import numpy as np
from numpy import pi
a=np.ones(3,dtype=np.int32)
b=np.linspace(0,pi,3)
b.dtype.name

'float64'

In [7]:
c=a+b
c

array([1.        , 2.57079633, 4.14159265])

In [6]:
c.dtype.name

'float64'

In [8]:
d=np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [9]:
d.dtype.name

'complex128'

In [11]:
rg=np.random.default_rng(1)
a = rg.random((2,3))
a

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [12]:
a.sum()

np.float64(3.290252281866131)

In [13]:
print(a.min())
print(a.max())


0.14415961271963373
0.9504636963259353


In [14]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
print(b.sum(axis=0))
print(b.sum(axis=1))

[12 15 18 21]
[ 6 22 38]


In [20]:
print(b.min(axis=1))
print(b.min(axis=0))

[0 4 8]
[0 1 2 3]


In [21]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [27]:
B=np.arange(3)
B

array([0, 1, 2])

In [24]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [25]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [29]:
C=np.array([2.,-1.,4.])
np.add(B,C)

array([2., 0., 6.])

In [30]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [31]:
a[2]

np.int64(8)

In [32]:
a[2:5]

array([ 8, 27, 64])

In [33]:
a[:6:2]

array([ 0,  8, 64])

In [34]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [38]:
for i in a:
    print(i**(i/3.))

1.0
1.0
255.99999999999991
7625597484987.0
3.402823669209368e+38
2.3509887016445483e+87
1.2041208676482352e+168
7.389715606740146e+289
inf
inf


C:\Users\admin\AppData\Local\Temp\ipykernel_16976\1257738107.py:2: RuntimeWarning: overflow encountered in scalar power
  print(i**(i/3.))


In [45]:
def f(x,y):
    return 10*x+y
b=np.fromfunction(f,(5,4),dtype=int)
print(b)
print(b[2,3])
print(b[0:5,1])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]


In [2]:
import numpy as np
c= np.array([[[0,1,2],[10,12,13]],[[100,102,102],[110,112,113]]])
c.shape

(2, 2, 3)

In [3]:
c[1,...]

array([[100, 102, 102],
       [110, 112, 113]])

In [4]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [7]:
for row in c:
    print(row)

[[ 0  1  2]
 [10 12 13]]
[[100 102 102]
 [110 112 113]]


In [8]:
for row in c.flat:
    print(row)

0
1
2
10
12
13
100
102
102
110
112
113


In [35]:
rg=np.random.default_rng(seed=42)
a=np.floor(10*rg.random((3,4)))
a

array([[7., 4., 8., 6.],
       [0., 9., 7., 7.],
       [1., 4., 3., 9.]])

In [11]:
a.shape

(3, 4)

In [13]:
a.ravel()

array([2., 9., 2., 2., 1., 3., 9., 5., 2., 6., 4., 7.])

In [14]:
a.reshape(6,2)

array([[2., 9.],
       [2., 2.],
       [1., 3.],
       [9., 5.],
       [2., 6.],
       [4., 7.]])

In [15]:
a.T

array([[2., 1., 2.],
       [9., 3., 6.],
       [2., 9., 4.],
       [2., 5., 7.]])

In [16]:
a.T.shape

(4, 3)

In [17]:
a.shape

(3, 4)

In [18]:
a.ravel(order="C")

array([2., 9., 2., 2., 1., 3., 9., 5., 2., 6., 4., 7.])

In [19]:
a.ravel(order="F")

array([2., 1., 2., 9., 3., 6., 2., 9., 4., 2., 5., 7.])

In [20]:
a

array([[2., 9., 2., 2.],
       [1., 3., 9., 5.],
       [2., 6., 4., 7.]])

In [22]:
a.resize((2,6))

In [23]:
a

array([[2., 9., 2., 2., 1., 3.],
       [9., 5., 2., 6., 4., 7.]])

In [24]:
a.reshape(3,-1)

array([[2., 9., 2., 2.],
       [1., 3., 9., 5.],
       [2., 6., 4., 7.]])

In [28]:
from numpy import newaxis
np.column_stack((a))

array([[2., 9.],
       [9., 5.],
       [2., 2.],
       [2., 6.],
       [1., 4.],
       [3., 7.]])

In [29]:
a=np.array([4.,2.])
b=np.array([3.,8.])

In [30]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [31]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [32]:
a[:,newaxis]

array([[4.],
       [2.]])

In [33]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [34]:
np.hstack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [41]:
a=np.arange(10)
np.random.choice(a,10,replace=False,p=None)

array([4, 9, 3, 8, 2, 0, 5, 7, 1, 6])

In [135]:
np.random.choice(5,size=3)

array([1, 1, 0], dtype=int32)

In [124]:
np.random.choice(5,size=3,replace=False)

array([4, 1, 0], dtype=int32)

In [161]:
arr=['apple','banana','cherry']
np.random.choice(arr,size=2)

array(['banana', 'cherry'], dtype='<U6')

In [184]:
np.random.choice([1,2,3],size=5,p=[0.7,0.2,0.1])

array([1, 1, 2, 1, 1])

In [186]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [191]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [194]:
np.ones((2,3),dtype=complex,order='F')

array([[1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j]])

In [195]:
np.full(5,7)

array([7, 7, 7, 7, 7])

In [197]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [200]:
np.full((2,2),3.5,dtype=float)

array([[3.5, 3.5],
       [3.5, 3.5]])

In [201]:
arr=np.array([10,15,20,25])
np.diff(arr)

array([5, 5, 5])

In [203]:
arr=np.array([[1,3,6],[2,5,9]])
np.diff(arr,axis=1)

array([[2, 3],
       [3, 4]])

In [208]:
arr=np.array([0,1,4,9,16])
np.diff(arr,n=1)
# first diff [1,3,5,7]
# second diff [2,2,2]
# third diff [0,0]
# fourth diff [0]

array([1, 3, 5, 7])

In [211]:
a=np.array([1.0,3.0,2.0])
b=np.array([1.0,2.0000001,2.9999])
print(np.allclose(a,b))

False


In [213]:
arr=np.array([1,2,3])
print(np.repeat(arr,2))

[1 1 2 2 3 3]


In [214]:
np.repeat([10,20,30],[1,2,3])

array([10, 20, 20, 30, 30, 30])

In [215]:
arr=np.array([[1,2],[3,4]])
print(np.repeat(arr,2))

[1 1 2 2 3 3 4 4]


In [217]:
print(np.repeat(arr,2,axis=0))

[[1 2]
 [1 2]
 [3 4]
 [3 4]]


In [218]:
print(np.repeat(arr,2,axis=1))

[[1 1 2 2]
 [3 3 4 4]]


In [221]:
arr=np.array([10,20,30,40,50])
idx=np.where(arr>20,1,0)
print(idx)

[0 0 1 1 1]


In [222]:
arr=np.array([[1,2,3],[4,5,6]])
print(np.where(arr%2==0,"even","odd"))

[['odd' 'even' 'odd']
 ['even' 'odd' 'even']]


In [223]:
arr=np.array([5,10,15,20])
val=arr[np.where(arr>10)]
print(val)

[15 20]


In [225]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [226]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [227]:
arr[arr%2==0]

array([10, 20])

In [1]:
import numpy as np

In [3]:
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([2,3,4])
print(arr2)

[1 2 3]
[2 3 4]


In [4]:
arr1 + arr2

array([3, 5, 7])

In [5]:
arr1 + 4

array([5, 6, 7])

In [6]:
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([[2],[4],[6]])
print(arr2)

[1 2 3]
[[2]
 [4]
 [6]]


In [7]:
arr1 + arr2

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [8]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6,7])

In [9]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [11]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1.ndim)
arr2=np.array([2,2,2])
print(arr2.ndim)
arr1+arr2

2
1


array([[3, 4, 5],
       [6, 7, 8]])

In [12]:
arr1=np.array([[1,2],[3,4],[5,6]])
arr2=np.array([2,2,2])
arr1+arr2

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [17]:
import numpy as np
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [25]:
arr_rg = gen(pcg(seed=101))
arr_rg.normal(size=(5,5))

array([[-0.7901525 , -2.03462548,  0.60330175,  0.74429453, -0.3096868 ],
       [ 0.36732137,  1.71039429,  1.06079784,  0.70763902,  0.68774939],
       [-0.86356745,  0.96401673, -1.64846282, -0.33209181, -0.43729384],
       [-1.72851871, -0.11033889,  1.64345508, -0.34012734, -1.20760334],
       [-0.09105372,  0.85392432,  0.19321812, -0.00266572, -1.40922226]])

In [20]:
arr_rg

Generator(PCG64) at 0x1FEA013D540

In [26]:
arr_rg=gen(pcg(seed=200))
arr_rg.integers(low=10, high=100, size=(5,5))

array([[13, 68, 31, 69, 40],
       [12, 58, 26, 90, 61],
       [49, 59, 52, 57, 52],
       [43, 73, 15, 70, 43],
       [50, 42, 72, 31, 66]])

In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr1+arr2

array([5, 7, 9])

In [3]:
arr=[1,2,3]
ar=[4,5,6]
arr+ar

[1, 2, 3, 4, 5, 6]