In [2]:
import numpy as np

In [ ]:
# Create a 1-D NumPy array of all even integers from 2 to 20 (inclusive).

In [3]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
np.linspace(2, 20, 10, dtype=np.int64)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
# Create a 2×3 NumPy array filled with zeros, then change the middle element (row=0, col=1) to 7. Print the updated array.

In [6]:
zero = np.zeros((2,3), dtype=int)
zero[0,1] = 7

In [7]:
zero

array([[0, 7, 0],
       [0, 0, 0]])

In [ ]:
# Take the 3×4 matrix 

In [8]:
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
arr[1]

array([5, 6, 7, 8])

In [ ]:
# From the same 3×4 array, extract the third column (all rows, column index 2). Print it as a 1-D array.

In [10]:
arr[:, 2]

array([ 3,  7, 11])

In [ ]:
# Take the same 3×4 array. 
# Extract the submatrix consisting of the last two rows and the last two columns. Print the result.

In [11]:
arr[-2:, -2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
# Generate a 4×4 identity matrix (1’s on the diagonal, 0’s elsewhere). 
# Then multiply every element by 5. Print the result.

In [12]:
identity = np.eye(4, dtype=int)
identity

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [13]:
identity*5

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 5]])

In [14]:
identity

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
# Create a NumPy array of shape (3,3) filled with values from 1 to 9. 
# Then compute the sum of each column. Print the result as a 1-D array.

In [15]:
arr = np.arange(1,10).reshape(3,3)
arr.sum(axis = 0)

array([12, 15, 18])

In [ ]:
# Given a 1-D array a = np.array([1, 2, 3, 4, 5]), 
# use boolean indexing to replace all values greater than 3 with 0`. 
# Print the modified array.

In [16]:
a = np.array([1, 2, 3, 4, 5])
mask = a > 3
a[ mask ] = 0
a

array([1, 2, 3, 0, 0])

In [ ]:
# Create a 1-D array x = np.array([1.0, 2.0, 3.0]) and a 1-D array y = np.array([10.0, 20.0, 30.0]). 
# Use broadcasting to compute x + y and x[:, None] * y (outer product). 
# Print both results and their shapes.

In [17]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([10.0, 20.0, 30.0])
total = x + y
result = x[:, None]*y
print(f"{total}\n Shape is : {total.shape}")
print(f"{result}\n Shape is : {result.shape}")

[11. 22. 33.]
 Shape is : (3,)
[[10. 20. 30.]
 [20. 40. 60.]
 [30. 60. 90.]]
 Shape is : (3, 3)


In [18]:
np.outer(x,y)

array([[10., 20., 30.],
       [20., 40., 60.],
       [30., 60., 90.]])

In [19]:
result

array([[10., 20., 30.],
       [20., 40., 60.],
       [30., 60., 90.]])

In [ ]:
# Set a random seed for reproducibility, then generate a 2×3 array of standard normal values. 
# Compute the mean of each column and the overall standard deviation. Print both results.

In [20]:
np.random.seed(32)
matrix = np.random.randn(2, 3)
mean = matrix.mean(axis = 0)
sd = matrix.std()
print(f"Mean of each column : {mean} \n Standard deviation : {sd}")

Mean of each column : [-0.13930501  0.88061805  0.58144079] 
 Standard deviation : 0.4488118117912318


In [21]:
matrix

array([[-0.34889445,  0.98370343,  0.58092283],
       [ 0.07028444,  0.77753268,  0.58195875]])

In [ ]:
# Using np.random.default_rng(123), generate a 1-D array of 10 integers from 0 to 99 (inclusive). 
# Replace all values less than 50 with their square, and values ≥50 with -1. 
# Print the final array and its dtype.

In [22]:
import numpy as np
rng = np.random.default_rng(0)
arr = rng.integers(0, 100, size = 10)
arr[arr < 50] = arr[arr < 50] ** 2
arr[arr >= 50] = -1
arr

array([-1, -1, -1, -1, -1, 16, 49,  1, -1, -1])

In [ ]:
# Given a 2-D array a with shape (4,5), compute the mean of each row, then subtract the corresponding row mean from each row (mean-centering). 
# Verify each resulting row has mean≈0 within atol=1e-12. Print the centered array and the verification result.
# Targets: broadcasting, keepdims/shape alignment, np.mean(axis=1), np.allclose

In [23]:
arr = np.arange(1,21).reshape(4,5)
mean = arr.mean(axis = 1, keepdims = True)
mean_center = arr - mean
verify = np.allclose(mean_center.mean(axis=1), 0, atol = 1e-12)
print(mean_center)
print(verify)

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]
True


In [ ]:
# Given a 10,000-length 1-D float array x, compute a rolling mean with window size 5 using only NumPy (no loops, no pandas). 
# Return an array of length 9,996 containing the valid-centered means. 
# Print the result’s first 5 values and its shape.

In [24]:
rng = np.random.default_rng()
x = rng.random(10000)
w_size = 5
stride = np.lib.stride_tricks.sliding_window_view(x, w_size)
rolling_mean = stride.mean(axis = 1)
print(rolling_mean[:5])
print(rolling_mean.shape)

[0.48339791 0.4300236  0.38954582 0.34118818 0.37108928]
(9996,)
